services:
  catalog1:
    build: ./catalog
    environment:
      DATABASE_FILENAME: "data_c1.db"
      INSTANCE_NAME: "catalog1"
      FRONTEND_SERVICE_URL: "http://frontend:3000" # <--- تمت إضافته
      OTHER_CATALOG_REPLICAS_URLS: "http://catalog2:4000" # <--- تمت إضافته
    volumes:
      - ./catalog/db_c1:/app/db
    networks:
      - bazar-network

  catalog2:
    build: ./catalog
    environment:
      DATABASE_FILENAME: "data_c2.db"
      INSTANCE_NAME: "catalog2"
      FRONTEND_SERVICE_URL: "http://frontend:3000" # <--- تمت إضافته
      OTHER_CATALOG_REPLICAS_URLS: "http://catalog1:4000" # <--- تمت إضافته
    volumes:
      - ./catalog/db_c2:/app/db
    networks:
      - bazar-network

  order1:
    build: ./order
    environment:
      DATABASE_FILENAME: "data_o1.db"
      INSTANCE_NAME: "order1"
      # متغير البيئة لـ order server إذا كان سيقرأ عناوين الكتالوج من هنا
      CATALOG_REPLICAS_URLS_FOR_ORDER: "http://catalog1:4000,http://catalog2:4000" # <--- تمت إضافته
    volumes:
      - ./order/db_o1:/app/db
    networks:
      - bazar-network
    depends_on:
      - catalog1
      - catalog2

  order2:
    build: ./order
    environment:
      DATABASE_FILENAME: "data_o2.db"
      INSTANCE_NAME: "order2"
      CATALOG_REPLICAS_URLS_FOR_ORDER: "http://catalog1:4000,http://catalog2:4000" # <--- تمت إضافته
    volumes:
      - ./order/db_o2:/app/db
    networks:
      - bazar-network
    depends_on:
      - catalog1
      - catalog2

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - bazar-network
    depends_on:
      - catalog1
      - catalog2
      - order1
      - order2
    environment:
      CATALOG_REPLICAS_URLS: "http://catalog1:4000,http://catalog2:4000"
      ORDER_REPLICAS_URLS: "http://order1:5000,http://order2:5000"
      # FRONTEND_SERVICE_URL لم نعد بحاجة إليه هنا لأن frontend لا يرسل طلبات لنفسه
      # ولكن order_server و catalog_server يحتاجان لعنوان frontend لإلغاء الكاش

networks:
  bazar-network:
    driver: bridge